---
# this playbook supports rolling updates, so it can be executed in batches of some server number percent. Also, playbook can run on all hosts in parallel (100%). 
# this playbook uses deploy_httpd_app ansible role
- hosts: webservers
  serial: "{{ server_percent | default('100') }}%"
  roles:
   - /ansible/deploy_httpd_app/
