---
# this playbook will not execute on all hosts in parallel, so rolling updates are supported. 
# here we run playbook in batches of 20% of servers
# this playbook uses deploy_httpd_app ansible role
- hosts: webservers
  serial: "20%"
  roles:
   - /ansible/deploy_httpd_app/
